#!/usr/bin/env bash

REMOTE_USER=$1

if [[ -z "${REMOTE_USER}" ]]; then
  echo "Usage: $0 <your-remote-user-name>"
  exit
fi

# Example:
declare -a servers=(
  "someuser@example.com"
  "${REMOTE_USER}@spin-staging.yourgolftravel.com"
)

for server in ${servers[@]}; do
  # More info about this solution:
  # - http://stackoverflow.com/questions/5768130/bash-ssh-test-for-public-key-authentication/5768198#5768198
  # - http://linuxcommando.blogspot.co.uk/2008/10/how-to-disable-ssh-host-key-checking.html
  ssh \
    -o 'BatchMode yes' \
    -o 'StrictHostKeyChecking no' \
    -o 'UserKnownHostsFile /dev/null' \
    "${server}" \
    true \
    > /dev/null 2>&1

  if [[ $? == 0 ]]; then
    echo "${server} -> OK"
  else
    echo "${server} -> Auth Failed"
  fi
done
