./etc/
./etc/sysconfig/
./etc/sysconfig/vncservers
./etc/init.d/
./etc/init.d/vncserver
./usr/
./usr/bin/
./usr/bin/Xvnc
./usr/bin/vncserver
./usr/bin/vncconfig
./usr/bin/vncpasswd
./usr/bin/vncviewer
./usr/bin/x0vncserver
./usr/share/
./usr/share/man/
./usr/share/man/man1/
./usr/share/man/man1/vncserver.1.gz
./usr/share/man/man1/Xvnc.1.gz
./usr/share/man/man1/x0vncserver.1.gz
./usr/share/man/man1/vncpasswd.1.gz
./usr/share/man/man1/vncconfig.1.gz
./usr/share/man/man1/vncviewer.1.gz
./usr/share/doc/
./usr/share/doc/tigervnc-license-1.3.0/
./usr/share/doc/tigervnc-license-1.3.0/LICENCE.TXT
./usr/share/doc/tigervnc-1.3.0/
./usr/share/doc/tigervnc-1.3.0/README.txt
./usr/share/doc/tigervnc-server-applet-1.3.0/
./usr/share/doc/tigervnc-server-applet-1.3.0/README
./usr/share/applications/
./usr/share/applications/vncviewer.desktop
./usr/share/locale/
./usr/share/locale/de/
./usr/share/locale/de/LC_MESSAGES/
./usr/share/locale/de/LC_MESSAGES/tigervnc.mo
./usr/share/locale/sv/
./usr/share/locale/sv/LC_MESSAGES/
./usr/share/locale/sv/LC_MESSAGES/tigervnc.mo
./usr/share/locale/ru/
./usr/share/locale/ru/LC_MESSAGES/
./usr/share/locale/ru/LC_MESSAGES/tigervnc.mo
./usr/share/locale/sk/
./usr/share/locale/sk/LC_MESSAGES/
./usr/share/locale/sk/LC_MESSAGES/tigervnc.mo
./usr/share/locale/pl/
./usr/share/locale/pl/LC_MESSAGES/
./usr/share/locale/pl/LC_MESSAGES/tigervnc.mo
./usr/share/locale/fr/
./usr/share/locale/fr/LC_MESSAGES/
./usr/share/locale/fr/LC_MESSAGES/tigervnc.mo
./usr/share/vnc/
./usr/share/vnc/classes/
./usr/share/vnc/classes/index.vnc
./usr/share/vnc/classes/VncViewer.jar
./usr/share/icons/
./usr/share/icons/hicolor/
./usr/share/icons/hicolor/scalable/
./usr/share/icons/hicolor/scalable/apps/
./usr/share/icons/hicolor/scalable/apps/tigervnc.svg
./usr/share/icons/hicolor/24x24/
./usr/share/icons/hicolor/24x24/apps/
./usr/share/icons/hicolor/24x24/apps/tigervnc.png
./usr/share/icons/hicolor/48x48/
./usr/share/icons/hicolor/48x48/apps/
./usr/share/icons/hicolor/48x48/apps/tigervnc.png
./usr/share/icons/hicolor/16x16/
./usr/share/icons/hicolor/16x16/apps/
./usr/share/icons/hicolor/16x16/apps/tigervnc.png
./usr/share/icons/hicolor/32x32/
./usr/share/icons/hicolor/32x32/apps/
./usr/share/icons/hicolor/32x32/apps/tigervnc.png
./usr/share/icons/hicolor/22x22/
./usr/share/icons/hicolor/22x22/apps/
./usr/share/icons/hicolor/22x22/apps/tigervnc.png
./usr/lib64/
./usr/lib64/dri/
./usr/lib64/dri/swrast_dri.so
./usr/lib64/xorg/
./usr/lib64/xorg/modules/
./usr/lib64/xorg/modules/extensions/
./usr/lib64/xorg/modules/extensions/libvnc.a
